Amadelli-TheBestAcai/thebestacai-gestor-de-vendas

README.md
=> Ajustando readme

src/containers/SalesHistory/index.tsx, src/containers/SalesHistory/styles.ts, src/pages/Sale/index.tsx
Adicionando borda de cor laranja para destacar venda selecionada.
=> Refactor - Adicionando estilização na venda selecionada

electron/src/helpers/BalanceFormater.ts, electron/src/models/gestor/balance.ts, src/models/dtos/balance.ts, src/pages/Balance/index.tsx
Feature - Adicionando card de desconto na tela de balanço
=> Feature - Card de desconto na tela de balanço

src/models/dtos/HandlerTotal.ts, src/pages/Handler/index.tsx, src/pages/Handler/styles.ts
Adicionando botão "Mais informações" para abrir modal para movimentações. Realizando soma de movimentações.
=> Feature/luis modal movimentações

electron/main.ts, electron/src/helpers/salesFormaterToIntegrate.ts, electron/src/models/dtos/nfe.ts, electron/src/models/gestor/sale.ts, electron/src/usecases/sale/emitNfce.ts, electron/src/usecases/sale/finishSale.ts, electron/src/usecases/sale/onlineIntegration.ts, src/containers/NfeForm/index.tsx, src/context/globalContext.tsx, src/models/dtos/sale.ts, src/models/dtos/salesFromApi.ts, src/pages/Nfce/index.tsx, src/pages/Sale/index.tsx
Foi adicionando dentro do payload do put de sales a coluna ref com a referencia da nfce, para criar o vinculo entre sales e nfce.
=> Create ref sales in nfce

src/pages/Settings/index.tsx
Page settings
- Adição de parseInt() na porta da balança.
=> fix - resolvendo números decimais na porta da balança

src/containers/SalesHistory/index.tsx, src/pages/Sale/index.tsx
Page Sales
- Remoção de .add(3, "hours") das informações de vendas.
=> fix - Removendo .add(3, "hours") de sales e saleslist

src/containers/SalesHistory/index.tsx
Page Sales
- Ajuste de flex direction ao selecionar tipo de lista
=> fix - Ajuste flexdirection list sales

src/context/globalContext.tsx
GlobalContext. QA ID#52: Alterar texto da notificação após adicionar nova comanda, "...modal anterior.", para "...janela/menu de comandas".
- Modificação no texto de notificação apresentado após adicionar nova comanda.
Obs: Modificação feita apenas na linha 309, as demais foram feitas pelo pettrier do vs-code.
=> Fix - Alterando texto pós adição de comanda

src/containers/RegistrationCard/index.tsx
Modal RegistrationCard. QA ID#51: Não tem Tooltip no botão para retornar a comanda.
- Adição de tooltip em retornar comanda.
=> Feature - Adicionando tooltip no botão de retornar comanda

electron/src/helpers/salesFormaterToIntegrate.ts, src/containers/Products/index.tsx
Ajustando a ordernação dos produtos do gestor para retornar por nome
=> Refact container products

src/pages/Sale/index.tsx, src/pages/Sale/styles.ts
alterando o texto de emitir nota fiscal e adicionando um cursor pointer.
=> refact: adicionando cursos pointer no texto

src/components/HandlerItem/index.tsx
Foi adicionado o tooltip de remover e imprimir na tela de movimentações
=> feat: add tooltip remover e imprimir

src/containers/SalesHistory/index.tsx, src/pages/Sale/index.tsx
Foi adicionado + 3 horas na visualização da venda na tela de vendas.
=> feat: add 3 horas na hora da venda

src/pages/StoreCash/index.tsx
Nesse pr adicionei um estado que verifica se foi aberto o caixa online, com isso ele não deixa que seja clicado varias vezes e seja aberto mais de um caixa por vez.
=> feat: add estado que abre o caixa

src/pages/Sale/index.tsx
=> refact: alterando resource da variavel de qrcode

elastic-mapping.json, electron/src/helpers/salesHistoryResponse.ts, electron/src/models/dtos/salesFromApi.ts, electron/src/models/gestor/product.ts, electron/src/models/gestor/sale.ts, src/models/dtos/item.ts, src/models/dtos/product.ts, src/models/dtos/salesFromApi.ts
Foi alterado o tipo da propriedade cod_ncm para string
=> Refact type cod ncm

src/pages/Balance/index.tsx, src/pages/Balance/styles.ts
Foi alterado a ordem em que os cards do balanço são mostrados
=> Refact cards of balance

src/pages/Nfce/index.tsx
Corrigido bug na tela de nfce que nao apagava o campo de texto quando a nota era emitida
=> refact: removendo textos da tela de nfce

.github/workflows/cd.yaml, .github/workflows/ci.yaml, README.md, electron/src/models/dtos/salesFromApi.ts, electron/src/usecases/common/printSale.ts
Foi adicionado um codigo hash no cupom fiscal.
=> feat: add codigo hash no cupom fiscal

electron/src/helpers/salesFormaterToIntegrate.ts, electron/src/helpers/salesHistoryResponse.ts, electron/src/models/dtos/salesFromApi.ts, electron/src/models/gestor/product.ts, electron/src/models/gestor/sale.ts, src/models/dtos/item.ts, src/models/dtos/product.ts, src/models/dtos/salesFromApi.ts
=> feat: add prop cest

src/components/AmountModal/index.tsx
Neste pr foi acrescentado a integração de vendas, movimentações e itens fora do carrinho ao clicar no botão fechar caixa.
=> feat: add integração de vendas ao fechar um caixa

electron/src/helpers/salesFormaterToIntegrate.ts, electron/src/models/dtos/salesFromApi.ts, electron/src/models/gestor/sale.ts, electron/src/usecases/common/printSale.ts, electron/src/usecases/sale/buildNewSale.ts, electron/src/usecases/sale/emitNfce.ts, package.json, src/containers/NfeForm/index.tsx, src/context/globalContext.tsx, src/models/dtos/sale.ts, src/models/dtos/salesFromApi.ts, src/pages/Sale/index.tsx, yarn.lock
Foi criado o fluxo de criar um token jwt e adiciona-lo no qr code de avaliação de campanha
=> feat: adicionando token no qrcode de avaliação 

electron/src/controllers/balanceController.ts, src/pages/Settings/index.tsx, src/pages/Settings/styles.ts
Adicionando botão que testa a conexão da balança na tela de configurações
=> Feat test connection balance

src/pages/StoreCash/index.tsx
Adicionando visualização do pix na parte de abertura/fechamento de caixa
=> feat: adicionando pix para visualização no fechamento do caixa

src/pages/Login/index.tsx
Foi ajustada a mensagem que retorna para o usuario quando o gestor precisa de uma nova atualização
=> refact: ajustando conteudo da mensagem sobre atualizar a versao do gestor

src/containers/ModalAddWaste/index.tsx
Adicionando campo de input para valor do disperdicio.
O campo de input retorna o valor do produto de acordo com o "price_sell"
=> feat: adicionando campo de input para valor do item

electron/src/factories/saleFactory.ts, electron/src/usecases/sale/getCustomerReward.ts, package.json, src/components/Item/index.tsx, src/components/Item/styles.ts, src/containers/RewardModal/index.tsx, src/containers/RewardModal/styles.ts, src/styles/GlobalStyle.ts
O que foi feito
- Ajuste do modal de recompensa, agora a recompensa será valida somente pelo Hashcode
- Ajuste de estilização do modal de recompensa
- Ajuste do motivo da exclusão do item, colocando um contador de caracteres
Testes feitos
-Teste de contador de caracteres FEITO
-Teste de usuario nao cadastrado FEITO
-Teste de expiração FEITO
-Teste de recompensa não esta ativa FEITO
-Teste de recompensa resgatada FEITO
-Teste de expiração de campanha FEITO
-Teste de expiração de recomppensa FEITO
-Teste de expiração de campanha mas a recompensa esta ativa FEITO
=> Pedro recompensa

src/containers/RewardModal/styles.ts
Ajuste de estilização do modal
=> style: ajuste de centralização do modal de hashcode

src/containers/RewardModal/styles.ts
Ajuste de estilização do modal
=> style: estilização modal

src/containers/Products/styles.ts, src/pages/Home/styles.ts
=> style: ajuste de overflow

src/containers/ModalAddWaste/index.tsx
=> feat: alteração de options

src/containers/ModalAddWaste/index.tsx
=> fix: ajuste de options

src/pages/Nfce/index.tsx
Ajuste de selfServiceAmount, o valor não estava zerando e assim setando o valor do selfServiceAmount com o price_unit(preço do selfservice)
=> fix: ajuste de nfce

src/components/ClientCPFInfo/index.tsx, src/components/Item/index.tsx, src/containers/Balance/index.tsx, src/containers/CupomModal/index.tsx, src/containers/DiscountForm/index.tsx, src/containers/InOutForm/index.tsx, src/containers/RegistrationCard/index.tsx, src/containers/RewardModal/index.tsx, src/context/globalContext.tsx
Ajuste do focus do input do valor da balança assim que abre os modais de "Cupom, Recompensa, Desconto, Entradas/Saidas, CPF"
=> fix: ajuste de focus dos inputs que abrem modal

src/pages/Settings/index.tsx, src/pages/Settings/styles.ts
estilização do campo de alterar loja
=> style: estilizando observação de alterar loja

electron/src/usecases/itemOutCart/integrationItemOutCart.ts, src/containers/RegistrationCard/index.tsx, src/containers/RegistrationCard/styles.ts
Ao excluir a comanda, vira itens out cart, criada as permissoes
=> Delete items command

src/containers/Balance/index.tsx, src/pages/Sale/index.tsx
Ajustes das casas decimais
https://ogrupothebest.atlassian.net/browse/AP-329
=> Ajuste casas decimais

package.json, src/components/AmountModal/index.tsx
Ajuste de modal de fechamento.
=> Ajuste fechamento

electron/src/models/gestor/store.ts, src/containers/InOutForm/index.tsx, src/pages/Login/index.tsx, src/pages/Nfce/index.tsx, src/pages/Nfce/styles.ts
Descrição no Jira
https://ogrupothebest.atlassian.net/browse/AP-1117
https://ogrupothebest.atlassian.net/browse/AP-1214
Pequeno ajuste na tela de login para listar somente empresas com country brasil.
Testes de fluxo de login, e todo o fluxo normal de vendas funcionando corretamente
=> Pedro ajuste numero negativo

electron/src/usecases/sale/getCustomerReward.ts, src/pages/Nfce/index.tsx
Descrição da task no Jira
https://ogrupothebest.atlassian.net/browse/AP-951
=> Pedro ajutes mensagem de recompensa

src/containers/Actions/index.tsx, src/containers/Actions/styles.ts
https://ogrupothebest.atlassian.net/browse/AP-1082
=> feat: ajuste de recompensa dentro da comanda

src/pages/Delivery/index.tsx
Ajustando bug que estava ocorrendo quando havia uma venda de delivery para ser registrada e um item no carrinho. A venda sumia e aparecia novamente na tela logo após um tempo
=> fix: ajustando venda de deliveru que estava sumindo

electron/main.ts, electron/src/factories/saleFactory.ts, electron/src/factories/storeCashFactory.ts, electron/src/usecases/storeCash/closeStoreCash.ts, package.json, src/components/AmountModal/index.tsx
Fix: Ajuste no problema em que o caixa fecha online porém permanece aberto offline impedindo seu fechamento.
=> Refact closed cash

src/pages/Sale/index.tsx
Ajuste estilização desconto, com currencyFormater.
=> fix: ajustando estilização do desconto

electron/src/usecases/common/printDanfe.ts, src/context/globalContext.tsx
Ajuste de danfe automatica na tela de HOME. A danfe estava sendo impressa sem o campo de desconto, foi incluido o campo de desconto para fazer a somatoria do desconto manual e também do desconto de cupom caso tenha.
=> fix: ajustando danfe automatico da tela de home

src/containers/Actions/index.tsx, src/containers/InOutForm/index.tsx
Ajustando envio de Saida para fornecedores e free lance para gerarem uma conta a pagar
=> fix: ajustando envio de free lance e fornecedores

package.json, src/context/globalContext.tsx
Ajuste de atualização de venda ao remover o item do carrinho
=> fix: ajustando remoção de venda

src/components/ClientCPFInfo/index.tsx
=> fix: retirando console
